//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiniela.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuinielaGolEntities : DbContext
    {
        public QuinielaGolEntities()
            : base("name=QuinielaGolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Prediction> Prediction { get; set; }
        public virtual DbSet<Ranking> Ranking { get; set; }
        public virtual DbSet<Match> Match { get; set; }
    }
}
